spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:../database/mydb
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect